/**
 * Drive one full demo run and write the evidence from what actually happened.
 *
 *   pnpm --filter @venue/console dev      # in another shell
 *   pnpm tsx scripts/capture.ts
 *
 * Writes `EVIDENCE-RUN.md`. Everything in it is read back from the running console and the
 * chain, so addresses and transaction hashes cannot drift out of step with the deployment
 * the way hand-transcribed ones do. Hashes are written in full: a truncated hash is not
 * evidence, because nobody can open it.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadEnv, publicClient, ROOT } from './lib/chain'

loadEnv()

const BASE = process.env.VENUE_CONSOLE_URL ?? 'http://localhost:3000'
const EXPLORER = 'https://testnet.monadscan.com'

interface TapeRow {
  kind: string
  text: string
  rule?: string
  txHash?: string
  travelRule?: { leg: string; reference: string | null; unavailable?: string }[]
}

interface State {
  proof: Record<string, string | number>
  asset: { address: string; symbol: string; name: string }
  limits: { maxHolders: number; holderCount: number }
  viewers: {
    key: string
    label: string
    address: string
    credential: { subTier: number } | null
    visible: { side: string }[]
    refusal: { reason: string; constraint: string } | null
  }[]
  tape: TapeRow[]
  latencyMs: number
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

async function state(): Promise<State> {
  const res = await fetch(`${BASE}/api/state`, { cache: 'no-store' })
  if (!res.ok) throw new Error(`GET /api/state -> ${res.status}`)
  return (await res.json()) as State
}

async function run(action: string): Promise<Record<string, unknown>> {
  const res = await fetch(`${BASE}/api/run`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action }),
  })
  return (await res.json()) as Record<string, unknown>
}

const pub = publicClient()

/** A hash is only evidence if it resolves - check rather than assert. */
async function receipt(hash: string) {
  return pub.getTransactionReceipt({ hash: hash as `0x${string}` })
}

async function main() {
  console.log(`capturing against ${BASE}`)

  console.log('  reset...')
  await run('reset')
  await sleep(3000)

  const opening = await state()
  const projections = opening.viewers.map((v) => ({
    key: v.key,
    label: v.label,
    address: v.address,
    subTier: v.credential?.subTier ?? null,
    asks: v.visible.filter((o) => o.side === 'ask').length,
    bids: v.visible.filter((o) => o.side === 'bid').length,
    refusal: v.refusal?.constraint ?? null,
  }))
  console.log(`  opening book: ${projections.map((p) => `${p.key}=${p.asks}/${p.bids}`).join(' ')}`)

  console.log('  two bids cross...')
  const crossed = await run('cross')
  await sleep(2000)

  console.log('  a credential lapses...')
  const lapsed = await run('lapse')
  await sleep(2000)

  const closing = await state()

  const fills = closing.tape.filter((r) => r.kind === 'fill' && r.txHash)
  const skips = closing.tape.filter((r) => r.kind === 'skipped')
  const lapses = closing.tape.filter((r) => r.kind === 'lapse')

  // Confirm every hash we are about to publish actually resolves on chain.
  const confirmed: { hash: string; block: bigint; gas: bigint; status: string }[] = []
  for (const hash of [
    ...fills.map((f) => f.txHash as string),
    ...(typeof lapsed.txHash === 'string' ? [lapsed.txHash] : []),
  ]) {
    const r = await receipt(hash)
    confirmed.push({ hash, block: r.blockNumber, gas: r.gasUsed, status: r.status })
    console.log(`  confirmed ${hash} (block ${r.blockNumber}, ${r.status})`)
  }

  const p = opening.proof
  const addr = (a: unknown) => `[\`${a}\`](${EXPLORER}/address/${a})`
  const tx = (h: string) => `[\`${h}\`](${EXPLORER}/tx/${h})`

  const lines: string[] = []
  lines.push('# Venue - captured demo run')
  lines.push('')
  lines.push(
    'Generated by `pnpm tsx scripts/capture.ts` against a running console. Every address and',
    'transaction below was read back from the chain in this run, and every hash is written in',
    'full so it can be opened.',
  )
  lines.push('')
  lines.push(`**Network:** ${p.network} (chainId ${p.chainId}) · explorer ${EXPLORER}`)
  lines.push('')
  lines.push('## Contracts')
  lines.push('')
  lines.push('| Role | Address |')
  lines.push('|---|---|')
  lines.push(`| \`Listed\` security (${opening.asset.symbol}) | ${addr(p.security)} |`)
  lines.push(`| Cash leg, Cleanverse aUSDC (not deployed by us) | ${addr(p.cash)} |`)
  lines.push(`| \`Settlement\` | ${addr(p.settlement)} |`)
  lines.push(`| \`MockPolicy\` | ${addr(p.policy)} |`)
  lines.push(`| Cleanverse CCP policy (not used for settlement) | ${addr(p.ccpPolicy)} |`)
  lines.push('')
  lines.push(`Rule set: \`${p.ruleSummary}\`.`)
  lines.push(
    `Holder cap ${opening.limits.holderCount}/${opening.limits.maxHolders}, so the cap binds from the opening block.`,
  )
  lines.push('')
  lines.push('## Beat 1 - three books, one asset')
  lines.push('')
  lines.push(
    'Credentials are resolved live from the Cleanverse CVI registry through `query_apass`,',
    'not from any contract we control. Sub-tiers below are what Cleanverse holds for these',
    'wallets.',
  )
  lines.push('')
  lines.push('| Viewer | CVI credential | Address | Asks | Bids | Refusal |')
  lines.push('|---|---|---|---|---|---|')
  for (const v of projections) {
    lines.push(
      `| [${v.key}] ${v.label} | sub-tier ${v.subTier ?? 'none'} | ${addr(v.address)} | ${v.asks} | ${v.bids} | ${v.refusal ?? '-'} |`,
    )
  }
  lines.push('')
  lines.push(`Projection latency: **${opening.latencyMs}ms** for all three viewers.`)
  lines.push('')
  lines.push('## Beat 2 - the holder cap binds')
  lines.push('')
  lines.push(
    `The matcher formed ${crossed.matched} match and passed over ${crossed.skipped} bid.`,
  )
  lines.push('')
  for (const s of skips) {
    lines.push(`- \`${s.text}\` - governing rule: \`${s.rule}\``)
  }
  lines.push('')
  lines.push('## Beat 3 - a credential lapses')
  lines.push('')
  lines.push(
    `Credential revoked for ${addr(lapsed.maker)}; the watcher cancelled ${lapsed.cancelled} resting order(s).`,
  )
  if (typeof lapsed.txHash === 'string') lines.push(`Revocation: ${tx(lapsed.txHash)}`)
  lines.push('')
  for (const l of lapses) lines.push(`- \`${l.text}\` - reason: \`${l.rule}\``)
  lines.push('')
  lines.push('## Beat 4 - delivery-versus-payment settles')
  lines.push('')
  for (const f of fills) {
    lines.push(`- \`${f.text}\``)
    lines.push(`  - transaction: ${tx(f.txHash as string)}`)
    for (const leg of f.travelRule ?? []) {
      lines.push(
        `  - Travel Rule (${leg.leg}): ${leg.reference ?? `unavailable, \`${leg.unavailable}\``}`,
      )
    }
  }
  lines.push('')
  lines.push('## Confirmed on chain')
  lines.push('')
  lines.push('| Transaction | Block | Gas | Status |')
  lines.push('|---|---|---|---|')
  for (const c of confirmed) {
    lines.push(`| ${tx(c.hash)} | ${c.block} | ${c.gas} | ${c.status} |`)
  }
  lines.push('')
  lines.push(
    `Zero reverts across the run: every refusal was formed off-chain and moved no value.`,
  )
  lines.push('')

  const out = join(ROOT, 'EVIDENCE-RUN.md')
  writeFileSync(out, `${lines.join('\n')}\n`)
  console.log(`\nwrote ${out}`)
  console.log(`  ${confirmed.length} transactions confirmed, full hashes`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
